# Generated by Django 5.0.7 on 2024-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
