# Generated by Django 5.1 on 2024-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='recipes/'),
        ),
    ]
