# Generated by Django 5.1 on 2024-09-05 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='anonymous', max_length=120),
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Intermediate', 'intermediate'), ('Hard', 'hard')], default='Easy', max_length=120),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions ...'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', help_text='Upload Image (Min.250px)', upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0, help_text='Enter the cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter each ingredient separated by a comma', max_length=250),
            preserve_default=False,
        ),
    ]
